modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="cmplxcore_materials" #mandatory
version="1.0.0" #mandatory
displayName="CMPLX Core: Materials" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://patreon.com/cmplx" #optional
logoFile="cmplxcorematerialsicon.png" #optional
credits="CMPLX, the Forge guys, and you, the community." #optional
authors="CMPLX" #optional
#mandatory
description='''
Some base materials for my other mods.
'''

[[dependencies.cmplxcore_materials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cmplxcore_materials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="BOTH"
